/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ObjectEntryVersion service. Represents a row in the &quot;ObjectEntryVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.object.model.impl.ObjectEntryVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.object.model.impl.ObjectEntryVersionImpl</code>.
 * </p>
 *
 * @author Marco Leo
 * @see ObjectEntryVersion
 * @generated
 */
@ProviderType
public interface ObjectEntryVersionModel
	extends BaseModel<ObjectEntryVersion>, ContainerModel, MVCCModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a object entry version model instance should use the {@link ObjectEntryVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this object entry version.
	 *
	 * @return the primary key of this object entry version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this object entry version.
	 *
	 * @param primaryKey the primary key of this object entry version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this object entry version.
	 *
	 * @return the mvcc version of this object entry version
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this object entry version.
	 *
	 * @param mvccVersion the mvcc version of this object entry version
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this object entry version.
	 *
	 * @return the uuid of this object entry version
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this object entry version.
	 *
	 * @param uuid the uuid of this object entry version
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the object entry version ID of this object entry version.
	 *
	 * @return the object entry version ID of this object entry version
	 */
	public long getObjectEntryVersionId();

	/**
	 * Sets the object entry version ID of this object entry version.
	 *
	 * @param objectEntryVersionId the object entry version ID of this object entry version
	 */
	public void setObjectEntryVersionId(long objectEntryVersionId);

	/**
	 * Returns the company ID of this object entry version.
	 *
	 * @return the company ID of this object entry version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this object entry version.
	 *
	 * @param companyId the company ID of this object entry version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this object entry version.
	 *
	 * @return the user ID of this object entry version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this object entry version.
	 *
	 * @param userId the user ID of this object entry version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this object entry version.
	 *
	 * @return the user uuid of this object entry version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this object entry version.
	 *
	 * @param userUuid the user uuid of this object entry version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this object entry version.
	 *
	 * @return the user name of this object entry version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this object entry version.
	 *
	 * @param userName the user name of this object entry version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this object entry version.
	 *
	 * @return the create date of this object entry version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this object entry version.
	 *
	 * @param createDate the create date of this object entry version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this object entry version.
	 *
	 * @return the modified date of this object entry version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this object entry version.
	 *
	 * @param modifiedDate the modified date of this object entry version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the object entry ID of this object entry version.
	 *
	 * @return the object entry ID of this object entry version
	 */
	public long getObjectEntryId();

	/**
	 * Sets the object entry ID of this object entry version.
	 *
	 * @param objectEntryId the object entry ID of this object entry version
	 */
	public void setObjectEntryId(long objectEntryId);

	/**
	 * Returns the content of this object entry version.
	 *
	 * @return the content of this object entry version
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this object entry version.
	 *
	 * @param content the content of this object entry version
	 */
	public void setContent(String content);

	/**
	 * Returns the version of this object entry version.
	 *
	 * @return the version of this object entry version
	 */
	public long getVersion();

	/**
	 * Sets the version of this object entry version.
	 *
	 * @param version the version of this object entry version
	 */
	public void setVersion(long version);

	/**
	 * Returns the status of this object entry version.
	 *
	 * @return the status of this object entry version
	 */
	public int getStatus();

	/**
	 * Sets the status of this object entry version.
	 *
	 * @param status the status of this object entry version
	 */
	public void setStatus(int status);

	/**
	 * Returns the container model ID of this object entry version.
	 *
	 * @return the container model ID of this object entry version
	 */
	@Override
	public long getContainerModelId();

	/**
	 * Sets the container model ID of this object entry version.
	 *
	 * @param containerModelId the container model ID of this object entry version
	 */
	@Override
	public void setContainerModelId(long containerModelId);

	/**
	 * Returns the container name of this object entry version.
	 *
	 * @return the container name of this object entry version
	 */
	@Override
	public String getContainerModelName();

	/**
	 * Returns the parent container model ID of this object entry version.
	 *
	 * @return the parent container model ID of this object entry version
	 */
	@Override
	public long getParentContainerModelId();

	/**
	 * Sets the parent container model ID of this object entry version.
	 *
	 * @param parentContainerModelId the parent container model ID of this object entry version
	 */
	@Override
	public void setParentContainerModelId(long parentContainerModelId);

	@Override
	public ObjectEntryVersion cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}